"""The hardest cases each study confirmed, as pictures: one figure per study.

For each study with a top_k goal, the settings its goal confirms (checked
now from the kept runs; first replicate of each arm, the arms in compare_proposers order, each
setting once), each shown by one failed run of that setting: the camera
frame at the failure (the triage thumbnail study_page.py made), the scene,
the knob values, and the triage's cause. Writes figures/gallery_<study>.png
and .pdf, and research/GALLERY.md with every case in words.

    uv run python research/harness/gallery.py
"""

import json
import sys
import textwrap
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parent))

from compare_proposers import arms
from goals import goal_status
from outer import history, results
from plot_results import SURFACE, TEXT, TEXT_SECONDARY, _save
from read_state import ROOT
from study_page import knob_text

STUDIES = ROOT / "research" / "studies"
PER_STUDY = 5


def cases(study: Path, plan: dict) -> list[dict]:
    """Confirmed settings with a triaged failed run that has a frame."""
    varied = tuple(plan["vary"])
    found, seen = [], set()
    for arm, folder in arms(study).items():
        triage_file = folder / "triage.json"
        if "_r" in arm or not triage_file.exists():
            continue
        rows = history(folder / "queue", varied)
        # The goal as code reads it now, not the goal.json the study wrote
        # when it stopped (the failure definition may have changed since).
        table = {row["id"]: row for row in results(rows, varied)}
        confirmed = goal_status(plan["goal"], list(table.values()), varied)["settings"]
        causes = {
            c["run"]: c for c in json.loads(triage_file.read_text(encoding="utf-8"))
        }
        for setting in confirmed:
            cell = table[setting]
            key = (cell["scene_id"], *(cell[k] for k in varied))
            if key in seen:
                continue
            for row in rows:
                frame = folder / "frames" / f"{row['run']}.png"
                same = (row["scene_id"], *(row[k] for k in varied)) == key
                if same and row["failed"] and row["run"] in causes and frame.exists():
                    seen.add(key)
                    found.append(
                        {
                            "arm": arm,
                            "run": row["run"],
                            "scene": cell["scene_id"][7:15],
                            "setting": ", ".join(knob_text(k, cell[k]) for k in varied),
                            "rate": f"{cell['failed']}/{cell['runs']} failed",
                            "cause": causes[row["run"]]["cause"].replace("_", " "),
                            "what": causes[row["run"]]["what_happened"],
                            "frame": frame,
                        }
                    )
                    break
    # One case per scene, as the goal asks for distinct scenes.
    by_scene = {}
    for case in found:
        by_scene.setdefault(case["scene"], case)
    return list(by_scene.values())[:PER_STUDY]


def main() -> int:
    lines = [
        "# The hardest cases found",
        "",
        "Generated by `harness/gallery.py`: each study's confirmed hardest",
        "settings (top_k goal, failure rate surely above the goal's bound by",
        "repeats), each with one failed run, its camera frame and the triage.",
        "",
    ]
    for study in sorted(p for p in STUDIES.iterdir() if (p / "plan.json").exists()):
        plan = json.loads((study / "plan.json").read_text(encoding="utf-8"))["plan"]
        if plan.get("goal", {}).get("type") != "top_k":
            continue
        found = cases(study, plan)
        if not found:
            continue
        lines += [f"## {study.name}", "", plan["question"], ""]
        fig, axes = plt.subplots(
            1, len(found), figsize=(2.6 * len(found), 2.9), facecolor=SURFACE
        )
        for ax, case in zip(axes if len(found) > 1 else [axes], found):
            ax.imshow(mpimg.imread(case["frame"]))
            ax.set_axis_off()
            ax.set_title(
                f"{case['scene']}\n{case['setting']}",
                fontsize=6.5,
                color=TEXT,
                loc="left",
            )
            ax.text(
                0,
                -0.04,
                textwrap.fill(f"{case['rate']}; {case['cause']}", 34),
                transform=ax.transAxes,
                fontsize=6,
                color=TEXT_SECONDARY,
                va="top",
            )
            lines.append(
                f"- **{case['scene']}**, {case['setting']} ({case['rate']}, found by "
                f"{case['arm']}): {case['cause']}. {case['what']} (`{case['run']}`)"
            )
        fig.tight_layout()
        _save(fig, f"gallery_{study.name}")
        lines += ["", f"![{study.name}](figures/gallery_{study.name}.png)", ""]
    (ROOT / "research" / "GALLERY.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
