"""What the gate did across every study: runs kept, retried and halted, and why.

Reads each study queue under research/studies (every arm and replicate; the
archived aborted_* folders are counted apart) and tallies the inner loop's
resolution of every attempt: ACCEPT (kept), RE-RUN or RESTART_CLEANUP (the
Investigator retried it; the retry is its own entry), HALT (stopped for a
person), or none yet (queued or running). Failed attempts are grouped by the
first check that failed (the k_status the Investigator saw). Writes
research/GATE.md and research/gate.json.

    uv run python research/harness/gate_report.py
"""

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from read_state import ROOT, load_entry, queue_entries

STUDIES = ROOT / "research" / "studies"


def first_check(k_status: str) -> str:
    """The failed check's name: the text before its first colon, with a
    wizard crash told apart by its cause where the log names one."""
    head = k_status.split(";")[0].split(":")[0].strip()
    return head or "unknown"


def tally(queues: list[Path]) -> dict:
    resolutions, reasons, by_reason_resolution = Counter(), Counter(), Counter()
    for queue in queues:
        for path in queue_entries(queue):
            entry = load_entry(path)
            resolution = entry["resolution"] or "pending"
            resolutions[resolution] += 1
            if entry["diagnosis"]:
                reason = first_check(entry["diagnosis"]["input"]["k_status"])
                reasons[reason] += 1
                by_reason_resolution[f"{reason} -> {resolution}"] += 1
    attempts = sum(resolutions.values()) - resolutions["pending"]
    return {
        "attempts": attempts,
        "kept": resolutions["ACCEPT"],
        "resolutions": dict(resolutions),
        "failed_checks": dict(reasons.most_common()),
        "outcomes": dict(by_reason_resolution.most_common()),
    }


def main() -> int:
    queues = sorted(STUDIES.rglob("queue"))
    live = [q for q in queues if "aborted_" not in str(q)]
    archived = [q for q in queues if "aborted_" in str(q)]
    report = {"studies": tally(live), "archived": tally(archived)}
    (ROOT / "research" / "gate.json").write_text(json.dumps(report, indent=1) + "\n")
    s = report["studies"]
    lines = [
        "# What the gate did",
        "",
        "Generated by `harness/gate_report.py` from every study queue (all arms",
        "and replicates). An attempt is one launch of a run; a retried run's",
        "retry is a new attempt. Archived aborted studies are counted apart.",
        "",
        f"- Attempts finished: {s['attempts']}; kept: {s['kept']} "
        f"({100 * s['kept'] / max(s['attempts'], 1):.1f}%).",
        "- Resolutions: "
        + ", ".join(f"{k} {v}" for k, v in sorted(s["resolutions"].items())),
        "",
        "| first failed check | resolution | attempts |",
        "|---|---|---|",
    ]
    for key, count in s["outcomes"].items():
        check, resolution = key.split(" -> ")
        lines.append(f"| {check} | {resolution} | {count} |")
    a = report["archived"]
    lines += [
        "",
        f"Archived (aborted studies): {a['attempts']} attempts, {a['kept']} kept; "
        + ", ".join(f"{k} {v}" for k, v in a["failed_checks"].items()),
    ]
    (ROOT / "research" / "GATE.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
