"""The mirror test: does VaVAM's left drift turn with the mirrored scene?

m1_queue runs each scene twice per seed: plain, and with the mirror switch
(the camera frames flipped left to right, LEFT and RIGHT commands swapped,
the plan mirrored back; run_experiment.launch_root). Same scene, seed and
traffic, so each pair differs only in the mirror. For every kept pair: the
ego's signed lateral offset from the recorded path (left positive,
drift_analysis.signed_offset) 3 s and 5 s after the hand-off and at the end,
and whether it failed. Then:

- mirrored runs drift right: the lean is the model's own (learned);
- mirrored runs barely drift: the model leans toward one side of the road as
  traffic in the scene shows it (a mirrored right-hand scene looks like
  left-hand traffic);
- mirrored runs still drift left: the lean comes from how the scene reaches
  the model, not from the model.

Writes research/MIRROR.md and research/mirror.json.

    uv run python research/harness/mirror_report.py
"""

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))

from drift_analysis import run_offsets
from read_state import ROOT, load_entry, mirror_request, queue_entries

QUEUE = ROOT / "research" / "harness" / "m1_queue"
SIDE_M = 0.5


def main() -> int:
    runs = {}
    for path in queue_entries(QUEUE):
        entry = load_entry(path)
        if entry["resolution"] != "ACCEPT" or "quarantine" in entry:
            continue
        config = entry["config"]
        key = (config["scene_id"][7:15], config["seed"])
        runs.setdefault(key, {})["mirror" if mirror_request(config) else "plain"] = (
            run_offsets(ROOT / entry["run_dir"])
        )
    pairs = {k: v for k, v in runs.items() if set(v) == {"plain", "mirror"}}
    rows = []
    for (scene, seed), pair in sorted(pairs.items()):
        row = {"scene": scene, "seed": seed}
        for side, result in pair.items():
            row[side] = {
                "at_3s": result["after"].get(3.0),
                "at_5s": result["after"].get(5.0),
                "at_end": result["at_end"],
                "failed": result["failed"],
            }
        rows.append(row)

    def summary(side: str) -> dict:
        end = np.array([r[side]["at_end"] for r in rows])
        return {
            "median_end_m": round(float(np.median(end)), 2) if len(end) else None,
            "left": int(np.sum(end > SIDE_M)),
            "right": int(np.sum(end < -SIDE_M)),
            "failed": sum(r[side]["failed"] for r in rows),
        }

    report = {
        "pairs": len(rows),
        "plain": summary("plain"),
        "mirror": summary("mirror"),
        "rows": rows,
    }
    (ROOT / "research" / "mirror.json").write_text(json.dumps(report, indent=1) + "\n")
    lines = [
        "# The mirror test",
        "",
        "Generated by `harness/mirror_report.py` from `harness/m1_queue`: each scene",
        "and seed run plain and mirrored (frames flipped, LEFT/RIGHT swapped, plan",
        "mirrored back), traffic replayed. Offsets from the recorded path, left",
        f"positive; left or right means more than {SIDE_M} m.",
        "",
        f"{len(rows)} kept pairs.",
        "",
        "| | median offset at the end | ended left | ended right | failed |",
        "|---|---|---|---|---|",
    ]
    for side in ("plain", "mirror"):
        s = report[side]
        lines.append(
            f"| {side} | {s['median_end_m']:+.2f} m | {s['left']} | {s['right']} "
            f"| {s['failed']} |"
            if rows
            else f"| {side} | - | - | - | - |"
        )
    lines += [
        "",
        "| scene | seed | plain +3 s | mirror +3 s | plain end | mirror end |",
        "|---|---|---|---|---|---|",
    ]
    fmt = lambda v: "-" if v is None else f"{v:+.2f}"  # noqa: E731
    for r in rows:
        lines.append(
            f"| {r['scene']} | {r['seed']} | {fmt(r['plain']['at_3s'])} "
            f"| {fmt(r['mirror']['at_3s'])} | {fmt(r['plain']['at_end'])} "
            f"| {fmt(r['mirror']['at_end'])} |"
        )
    (ROOT / "research" / "MIRROR.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
